name: Build and Deploy

on:
  push:
    branches:
      - main # Ändere dies auf deinen Hauptbranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            yourdockerhubusername/home-control-fetcher:latest
            yourdockerhubusername/home-control-ingestor:latest
            yourdockerhubusername/home-control-seeder:latest
