name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Determine changed services
        id: vars
        run: |
          SHARED_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E 'backend/sharedlib/*' | wc -l)
          FETCHER_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E 'backend/fetcher/*' | wc -l)
          INGESTOR_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E 'backend/ingestor/*' | wc -l)
          SEEDER_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E 'backend/seeder/*' | wc -l)
          SERVER_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E 'backend/server/*|frontend/*' | wc -l)

          echo "sharedlib_changed=$SHARED_CHANGED" >> $GITHUB_ENV
          echo "fetcher_changed=$FETCHER_CHANGED" >> $GITHUB_ENV
          echo "ingestor_changed=$INGESTOR_CHANGED" >> $GITHUB_ENV
          echo "seeder_changed=$SEEDER_CHANGED" >> $GITHUB_ENV
          echo "server_changed=$SERVER_CHANGED" >> $GITHUB_ENV

      - name: Build and push Docker images
        if: env.sharedlib_changed == '1' || env.fetcher_changed == '1'
        run: |
          docker build -t rsiegfanz/home-control-fetcher ./backend/fetcher
          docker push rsiegfanz/home-control-fetcher

      - name: Build and push Docker images
        if: env.sharedlib_changed == '1' || env.ingestor_changed == '1'
        run: |
          docker build -t rsiegfanz/home-control-ingestor ./backend/ingestor
          docker push rsiegfanz/home-control-ingestor

      - name: Build and push Docker images
        if: env.sharedlib_changed == '1' || env.seeder_changed == '1'
        run: |
          docker build -t rsiegfanz/home-control-seeder ./backend/seeder
          docker push rsiegfanz/home-control-seeder

      - name: Build and push Docker images
        if: env.sharedlib_changed == '1' || env.server_changed == '1'
        run: |
          docker build -t rsiegfanz/home-control-server ./backend/server
          docker push rsiegfanz/home-control-server
