services:
  postgres:
    image: postgres:16.4
    container_name: postgres_home_control
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-home_control_db}
      POSTGRES_USER: ${POSTGRES_USER:-home_control_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-home_control_password}
    volumes:
      - d:/dev/docker/share/home-control/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - home_control_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_home_control
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@home-control.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "5050:80"
    networks:
      - home_control_network

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_METADATA_LOG_DIR: /var/lib/kafka/kraft
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 1

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      CLUSTER_ID: "tTzszS7rTBeUOZxEcBeKUQ"
    volumes:
      - d:/dev/docker/share/home-control/kafka:/var/lib/kafka/data
      - ./metadata:/var/lib/kafka/kraft
    networks:
      - home_control_network

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - home_control_network

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - d:/dev/docker/share/home-control/promtail:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - home_control_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - home_control_network
networks:
  home_control_network:
    driver: bridge
