export enum RoomId {
    GARAGE = 1,

    GROUND_FLOOR_LIVING_ROOM = 10,
    GROUND_FLOOR_KITCHEN = 11,

    FIRST_FLOOR_LIVING_ROOM = 20,
    FIRST_FLOOR_KITCHEN = 21,
    FIRST_FLOOR_BEDROOM = 22,
    FIRST_FLOOR_GALLERY = 23,

    BASEMENT_GUEST_ROOM = 30,
    BASEMENT_GYM = 31,
}
