export enum RoomId {
    GARAGE = 1,

    GROUND_FLOOR_LIVING_ROOM = 10,
    GROUND_FLOOR_KITCHEN = 11,

    FIRST_FLOOR_LIVING_ROOM = 20,
    FIRST_FLOOR_KITCHEN = 21,
    FIRST_FLOOR_BEDROOM = 22,
    FIRST_FLOOR_GALLERY = 23,

    BASEMENT_GUEST_ROOM = 30,
    BASEMENT_GYM = 31,
}

export enum RoomNames {
    GARAGE = 'Garage',
    GROUNDFLOOR_LIVINGROOM = 'EG Wohnzimmer',
    GROUNDFLOOR_KITCHEN = 'EG Küche',
    UPPERFLOOR_LIVINGROOM = 'OG Wohnzimmer',
    UPPERFLOOR_KITCHEN = 'OG Küche',
    UPPERFLOOR_BEDROOM = 'OG Schlafzimmer',
    UPPERFLOOR_GALLERY = 'OG Empore',
    BASEMENTFLOOR_GUESTROOM = 'UG Gästezimmer',
    BASEMENTFLOOR_GYM = 'UG Fitnessraum',
}
