name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize changes.txt
        run: echo "" > changes.txt
        shell: bash

      - name: Initialize services_to_build.txt
        run: echo "" > services_to_build.txt
        shell: bash

      - name: Get Changes
        run: |
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            echo "This is a shallow clone. Fetching full history..."
            git fetch --unshallow
          fi

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Checking changes for the PR..."
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changes.txt
          else
            echo "Checking changes since the last commit..."
            if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
              git diff --name-only HEAD^ HEAD > changes.txt
            else
              echo "No previous commit found. Building all images."
              echo "backend/fetcher" > changes.txt
              echo "backend/ingestor" >> changes.txt
              echo "backend/seeder" >> changes.txt
              echo "backend/server" >> changes.txt
            fi
          fi

          echo "Changes detected:"
          cat changes.txt

        shell: bash

      - name: Read Changes
        run: |
          if grep -q "sharedlib" changes.txt; then
            echo "Shared library has changed. Building all services."
            echo "fetcher" >> services_to_build.txt
            echo "ingestor" >> services_to_build.txt
            echo "seeder" >> services_to_build.txt
            echo "server" >> services_to_build.txt
          else
            if grep -q "backend/fetcher" changes.txt; then
              echo "Fetcher has changed."
              echo "fetcher" >> services_to_build.txt
            fi
            if grep -q "backend/ingestor" changes.txt; then
              echo "Ingestor has changed."
              echo "ingestor" >> services_to_build.txt
            fi
            if grep -q "backend/seeder" changes.txt; then
              echo "Seeder has changed."
              echo "seeder" >> services_to_build.txt
            fi
            if grep -q "backend/server" changes.txt || grep -q "frontend" changes.txt; then
              echo "Server or frontend has changed."
              echo "server" >> services_to_build.txt
            fi
          fi
          echo "Services to build: $(cat services_to_build.txt)"
        shell: bash

      - name: Check for Services to Build
        run: |
          if [ ! -s services_to_build.txt ]; then
            echo "No services to build. Exiting."
            exit 0
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Images
        if: success()
        run: |
          while read service; do
            echo "Building and pushing $service..."
            docker buildx build \
              --cache-from type=local,src=/tmp/.buildx-cache \
              --cache-to type=local,dest=/tmp/.buildx-cache-new \
              --tag rsiegfanz/home-control-$service:${{ github.sha }} \
              --tag rsiegfanz/home-control-$service:latest \
              --file ./backend/$service/Dockerfile \
              --push \
              .
              echo "Finished building and pushing $service"
            done < services_to_build.txt
            echo "All builds completed successfully"

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Scan Docker Images
        run: |
          while read service; do
            echo "Scanning $service..."
            trivy image rsiegfanz/home-control-$service:latest
          done < services_to_build.txt

      - name: Cleanup
        if: always()
        run: rm -f changes.txt services_to_build.txt

      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          BUILD_STATUS="Success"
          if [ "${{ job.status }}" != "success" ]; then
            BUILD_STATUS="Failure"
          fi
          MESSAGE="Build Status: $BUILD_STATUS%0A"
          MESSAGE+="Repository: ${{ github.repository }}%0A"
          MESSAGE+="Branch: ${{ github.ref_name }}%0A"
          MESSAGE+="Commit: ${{ github.sha }}%0A"
          MESSAGE+="Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="$MESSAGE"
